name: Build # TODO: Reuse this workflow in other workflows

on:
  workflow_call:
    inputs:
      version:
        description: "Verion to build as"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Download Rodin dev package
        run: wget -O /var/tmp/org.rodinp.dev-3.6.0-77c344946.zip https://sourceforge.net/projects/rodin-b-sharp/files/Core_Rodin_Platform/3.6/org.rodinp.dev-3.6.0-77c344946.zip/download

      - name: Replace version in manifest file
        run: sed '/^Bundle-Version:/ s/[[:digit:]][[:digit:]]*.[[:digit:]][[:digit:]]*.[[:digit:]][[:digit:]]*.qualifier/'${{ inputs.version }}'.qualifier/g' -i fr.loria.dedale.bsimu/META-INF/MANIFEST.MF

      - name: Build with Maven
        run: mvn -Dtycho.localArtifacts=ignore -DforceContextQualifier="$(git log -1 --format='%h')" -Dplugin.version.number=${{ inputs.version }} clean package

      - name: Publish
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -Dplugin.version.number=${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
